"""Assemble Table 1 LaTeX macros from correctness suite JSON results.

Reads results/correctness_suite/<timestamp>/{part1,part3,part4}.json and
writes docs/WyckoffGNN_v6_2_Overleaf/WyckoffGNN_v6_2_Overleaf/tab_consistency_values.tex.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _fmt_sci(val: float, unit: str = "") -> str:
    """Format a float in scientific notation for LaTeX."""
    if val == 0.0:
        return f"0{unit}"
    import math
    exp = int(math.floor(math.log10(abs(val))))
    mantissa = val / (10 ** exp)
    return f"${mantissa:.1f}\\times10^{{{exp}}}${unit}"


def assemble(
    results_dir: str,
    output_path: str | None = None,
) -> str:
    """Read JSON results and produce LaTeX macro file.

    Args:
        results_dir: Path to timestamped results directory.
        output_path: Where to write the .tex file. If None, returns string.

    Returns:
        LaTeX content string.
    """
    results_path = Path(results_dir)

    part1_data = {}
    part3_data = {}
    part4_data = {}

    p1_file = results_path / "part1.json"
    if p1_file.exists():
        with open(p1_file) as f:
            part1_data = json.load(f)

    p3_file = results_path / "part3.json"
    if p3_file.exists():
        with open(p3_file) as f:
            part3_data = json.load(f)

    p4_file = results_path / "part4.json"
    if p4_file.exists():
        with open(p4_file) as f:
            part4_data = json.load(f)

    neighbor_max_err = 0.0
    if isinstance(part1_data, list):
        for struct_res in part1_data:
            neighbor_max_err = max(
                neighbor_max_err,
                struct_res.get("max_vec_err_all_sites", 0.0),
            )
    elif isinstance(part1_data, dict):
        neighbor_max_err = part1_data.get("max_vec_err_all_sites", 0.0)

    # Part 2 was removed: cross-view comparison is conceptually invalid
    # (quotient has site-symmetry projectors, P1-view does not; intermediate
    # hidden states are not expected to match)
    layerwise_str = "Removed"
    output_str = "Removed"
    gradient_str = "Removed"

    delta_rep = 0.0
    delta_transport = 0.0
    equiv_err_proper = 0.0
    equiv_err_improper = 0.0

    if "delta_rep" in part4_data:
        delta_rep = part4_data["delta_rep"].get("max_canonical", 0.0)
    if "delta_transport" in part4_data:
        delta_transport = part4_data["delta_transport"].get("max_proj_canonical", 0.0)
    if "equivariance_error" in part4_data:
        equiv_err_proper = part4_data["equivariance_error"].get("max_canonical_proper", 0.0)
        equiv_err_improper = part4_data["equivariance_error"].get("max_canonical_improper", 0.0)
        equiv_err_proper = max(
            equiv_err_proper,
            part4_data["equivariance_error"].get("max_benchmark_proper", 0.0),
        )
        equiv_err_improper = max(
            equiv_err_improper,
            part4_data["equivariance_error"].get("max_benchmark_improper", 0.0),
        )

    projector_idempotency = 0.0
    projector_stab_invariance = 0.0
    if isinstance(part3_data, dict):
        canonical_list = part3_data.get("canonical", [])
        benchmark = part3_data.get("benchmark", {})
        for struct_res in canonical_list:
            for orbit in struct_res.get("orbits", []):
                for ir in orbit.get("irreps", []):
                    projector_idempotency = max(
                        projector_idempotency, ir.get("idempotency", 0.0)
                    )
                    projector_stab_invariance = max(
                        projector_stab_invariance, ir.get("symmetry", 0.0)
                    )
        if benchmark:
            projector_idempotency = max(
                projector_idempotency,
                benchmark.get("max_idempotency", 0.0),
            )
            projector_stab_invariance = max(
                projector_stab_invariance,
                benchmark.get("max_stab_invariance", 0.0),
            )
    elif isinstance(part3_data, list):
        for struct_res in part3_data:
            for orbit in struct_res.get("orbits", []):
                for ir in orbit.get("irreps", []):
                    projector_idempotency = max(
                        projector_idempotency, ir.get("idempotency", 0.0)
                    )
                    projector_stab_invariance = max(
                        projector_stab_invariance, ir.get("symmetry", 0.0)
                    )

    neighbor_str = _fmt_sci(neighbor_max_err, r"~\AA")
    delta_rep_str = _fmt_sci(delta_rep)
    delta_transport_str = _fmt_sci(delta_transport)
    equiv_str = _fmt_sci(max(equiv_err_proper, equiv_err_improper))
    idemp_str = _fmt_sci(projector_idempotency)
    stab_str = _fmt_sci(projector_stab_invariance)

    lines = [
        f"% Generated by assemble_table1.py from {results_dir}",
        f"\\newcommand{{\\ConsistencyNeighborMaxErr}}{{{neighbor_str}}}",
        f"\\newcommand{{\\ConsistencyLayerwiseMax}}{{{layerwise_str}}}",
        f"\\newcommand{{\\ConsistencyOutputMax}}{{{output_str}}}",
        f"\\newcommand{{\\ConsistencyGradientMax}}{{{gradient_str}}}",
        f"\\newcommand{{\\ConsistencyDeltaRep}}{{{delta_rep_str}}}",
        f"\\newcommand{{\\ConsistencyDeltaTransport}}{{{delta_transport_str}}}",
        f"\\newcommand{{\\ConsistencyEquivariance}}{{{equiv_str}}}",
        f"\\newcommand{{\\ProjectorIdempotency}}{{{idemp_str}}}",
        f"\\newcommand{{\\ProjectorStabInvariance}}{{{stab_str}}}",
    ]
    content = "\n".join(lines) + "\n"

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(content)

    return content


def main():
    if len(sys.argv) < 2:
        print("Usage: python assemble_table1.py <results_dir> [output.tex]")
        sys.exit(1)

    results_dir = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    content = assemble(results_dir, output_path)
    print(content)
    if output_path:
        print(f"Written to {output_path}")


if __name__ == "__main__":
    main()
